apiVersion: v1
kind: Service
metadata:
  name: kross-etcd
spec:
  ports:
    - name: client
      nodePort: 32379
      port: 2379
      targetPort: 2379
      protocol: TCP
    - name: peers
      nodePort: 32380
      port: 2380
      targetPort: 2380
      protocol: TCP
  type: NodePort
  selector:
    app: kross-etcd
---
apiVersion: v1
kind: Pod
metadata:
  name: kross-etcd-192.168.56.5-0
  labels:
    app: kross-etcd
spec:
  containers:
  - image: quay.mirrors.ustc.edu.cn/coreos/etcd
    name: etcd
    ports:
    - containerPort: 2379
    - containerPort: 2380
    command:
    - /bin/sh
    - -ecx
    - |
      exec etcd --name kross-etcd-192.168.56.5-0 \
        --listen-peer-urls http://0.0.0.0:2380 \
        --listen-client-urls http://0.0.0.0:2379 \
        --advertise-client-urls http://192.168.56.5:32379 \
        --initial-advertise-peer-urls http://192.168.56.5:32380 \
        --initial-cluster-token etcd-cluster \
        --initial-cluster kross-etcd-192.168.56.5-0=http://192.168.56.5:32380 \
        --initial-cluster-state new