apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-server
spec:
  selector:
    matchLabels:
      app: simple-server
  replicas: 2
  template:
    metadata:
      labels:
        app: simple-server
    spec:
      containers:
      - name: simple-server
        image: easzlab.io.local:5000/simple-server
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: simple-server-svc
  annotations:
    kross: |
      {
        "exposure": ["http"]
      }
spec:
  type: NodePort
  selector:
    app: simple-server
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
    nodePort: 30010