apiVersion: v1
kind: ServiceAccount
metadata:
  name: kross-serviceaccount
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kross-clusterrole
rules:
- apiGroups: [""]
  resources: ["services", "pods"]
  verbs: ["get", "watch", "list", "create", "delete", "deletecollection"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kross-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: kross-serviceaccount
  namespace: default
roleRef:
  kind: ClusterRole
  name: kross-clusterrole
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: kross
  labels:
    app: kross
spec:
  serviceAccountName: kross-serviceaccount
  containers:
  - image: calvincui/kross
    name: kross
    ports:
    - containerPort: 7890
    volumeMounts:
    - name: config-file
      mountPath: /kross/config.yaml
    - name: secret #if you need
      mountPath: /kross/secret
  volumes:
  - name: config-file
    hostPath:
      path: #your config file path
  - name: secret #if you need
    hostPath:
      path: #your secret file path, e.g. ca_cert.pem
---
apiVersion: v1
kind: Service
metadata:
  name: kross-svc
  labels:
    app: kross
spec:
  type: NodePort
  ports:
  - port: 7890
    targetPort: 7890 #container port in config.yaml
    protocol: TCP
    nodePort: 30789 #default node port
    name: kross-port
  selector:
    app: kross
