apiVersion: v1
kind: ServiceAccount
metadata:
  name: kross-serviceaccount
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kross-role
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "watch", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-service-role-binding
subjects:
- kind: ServiceAccount
  name: kross-serviceaccount
  namespace: default
roleRef:
  kind: ClusterRole
  name: kross-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: kross
spec:
  serviceAccountName: kross-serviceaccount
  containers:
  - image: easzlab.io.local:5000/kross
    name: kross
    command: ["sh", "-c", "sleep 36000"]
